# Generated by Django 3.1.5 on 2021-05-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('shoppinglists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingListEntry',
            new_name='ShoppingEntry',
        ),
    ]
