# Generated by Django 3.1.5 on 2021-05-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0002_auto_20210522_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='checked',
        ),
    ]
