# Generated by Django 3.1.5 on 2021-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0002_auto_20210503_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
