<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-03-08 14:20
=======
# Generated by Django 3.1.5 on 2021-03-22 12:57
>>>>>>> origin/recipes

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('fd_category_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
=======
                ('scientific_name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('0', 'protein'), ('1', 'fruit'), ('2', 'vegetable'), ('3', 'dairy'), ('4', 'fat')], default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('py_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/recipes
            ],
        ),
    ]
