# Generated by Django 3.1.5 on 2021-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
                ('fd_category_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
