# Generated by Django 3.1.5 on 2021-02-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='scientific_name',
            new_name='name',
        ),
    ]
