# Generated by Django 3.1.5 on 2021-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fd_category',
            field=models.CharField(choices=[('0', 'protein'), ('1', 'fruit'), ('2', 'vegetable'), ('3', 'dairy'), ('4', 'fat')], default=None, max_length=32),
        ),
    ]
