# Generated by Django 3.1.5 on 2021-02-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20210220_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='scientific_name',
        ),
    ]
