# Generated by Django 3.1.5 on 2021-02-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20210221_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
