# Generated by Django 3.1.5 on 2021-03-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20210221_0248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_nutrient',
        ),
    ]
