# Generated by Django 3.1.5 on 2021-03-16 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0005_auto_20210221_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredients', models.ManyToManyField(to='ingredients.Food')),
            ],
        ),
    ]
