# Generated by Django 3.1.5 on 2021-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20210316_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='scientific_name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
