# Generated by Django 3.1.5 on 2021-03-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_delete_food_nutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=32)),
                ('protein_value', models.CharField(max_length=32)),
                ('fat_value', models.CharField(max_length=32)),
                ('carbohydrate_value', models.CharField(max_length=32)),
                ('fd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.food')),
            ],
        ),
    ]
