# Generated by Django 3.1.5 on 2021-03-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0006_auto_20210316_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('req_ingredients', models.ManyToManyField(related_name='req_ingredients', to='ingredients.Food')),
            ],
        ),
    ]
