# Generated by Django 3.1.5 on 2021-05-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210514_1135'),
        ('recipes', '0002_auto_20210511_1415'),
    ]

    operations = [
    ]
