# Generated by Django 3.1.5 on 2021-05-22 01:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210522_0115'),
        ('pantrys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='recipes.food'),
        ),
    ]
