# Generated by Django 3.1.5 on 2021-05-23 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210522_0115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pantrys', '0002_auto_20210522_0121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useringredient',
            unique_together={('food', 'user')},
        ),
    ]
