# Generated by Django 3.1.5 on 2021-05-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantrys', '0003_auto_20210523_1324'),
        ('pantrys', '0003_auto_20210523_1323'),
    ]

    operations = [
    ]
