# Generated by Django 3.1.5 on 2021-05-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantrys', '0004_merge_20210523_1746'),
        ('pantrys', '0004_merge_20210523_1741'),
    ]

    operations = [
    ]
