# Generated by Django 3.1.5 on 2021-05-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210524_1629'),
        ('pantrys', '0005_merge_20210523_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.food'),
        ),
    ]
